### ISSUE TITLE
Record 9/27 Facebook Live announcement.

### ISSUE THREAD

**Issue by justinhester** [justinhester/hwfam#11]
- Record on Kevin's phone
- Start with 20 push-ups (casual vibe)
# Questions
- What are you thoughts today on the news claw back?
- Amount?
- So, Kevin? How do you feel about the claw back?

1. announce tomorrow's more formal q&a
2. announce clyad event date

**Comment by justinhester** [comment]
1. Give update about situation
2. Announce official NYCAD
3. request feedback in comments
4. how much should trump give back?

**Comment by justinhester** [comment]
# Questions
[GreenEyes DG: can removing their sales goals make a difference?](https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Fcloseyouraccount%2Fposts%2F1786666848223252&width=500)

**Comment by iamlily** [comment]
**Current News/Update:**
Trump and Hillary 
How the movement is doing
Recent News
regarding case
strumpf and potential clawback

**Announcement**
50K+ shares
Announce national cya day
credit union q/a for tomorrow
7pm Facebook live

**Possible mention once confirmed:**
Forbes/CNN news
